from pathlib import Path

import pandas as pd


BASE_DIR = Path(__file__).resolve().parents[1]

OUTPUT_PATH = BASE_DIR / "data" / "metadata" / "plan_b_manual_coordinate_corrections.csv"

SELECTION_BASIS = (
    "Kandidat top kab/kot sentra tanaman pangan untuk padi, jagung, "
    "kacang tanah, dan kacang hijau; perlu validasi dengan data produksi kab/kot 2020-2024"
)

SELECTION_METHOD = "draft_top_food_crop_candidate"

rows = [
    {
        "province": "Aceh",
        "city_regency": "Aceh Utara",
        "selection_basis": SELECTION_BASIS,
        "selection_method": SELECTION_METHOD,
        "geocoding_query": "Lhoksukon",
        "matched_name": "Lhoksukon",
        "latitude": 5.051701,
        "longitude": 97.318123,
        "elevation": None,
        "country_code": "ID",
        "country": "Indonesia",
        "admin1": "Aceh",
        "admin2": "Aceh Utara Regency",
        "admin3": "",
        "timezone": "Asia/Jakarta",
        "population": None,
        "source": "Manual correction based on validated coordinate",
    },
    {
        "province": "Aceh",
        "city_regency": "Aceh Besar",
        "selection_basis": SELECTION_BASIS,
        "selection_method": SELECTION_METHOD,
        "geocoding_query": "Kota Jantho",
        "matched_name": "Kota Jantho",
        "latitude": 5.187659,
        "longitude": 95.715548,
        "elevation": None,
        "country_code": "ID",
        "country": "Indonesia",
        "admin1": "Aceh",
        "admin2": "Aceh Besar Regency",
        "admin3": "",
        "timezone": "Asia/Jakarta",
        "population": None,
        "source": "Manual correction based on validated coordinate",
    },
    {
        "province": "Aceh",
        "city_regency": "Bireuen",
        "selection_basis": SELECTION_BASIS,
        "selection_method": SELECTION_METHOD,
        "geocoding_query": "Bireuen",
        "matched_name": "Bireuen",
        "latitude": 5.203000,
        "longitude": 96.701000,
        "elevation": None,
        "country_code": "ID",
        "country": "Indonesia",
        "admin1": "Aceh",
        "admin2": "Bireuen Regency",
        "admin3": "Kota Juang",
        "timezone": "Asia/Jakarta",
        "population": None,
        "source": "Manual correction based on validated coordinate",
    },
    {
        "province": "Riau",
        "city_regency": "Rokan Hilir",
        "selection_basis": SELECTION_BASIS,
        "selection_method": SELECTION_METHOD,
        "geocoding_query": "Bagansiapiapi",
        "matched_name": "Bagansiapiapi",
        "latitude": 2.156680,
        "longitude": 100.807630,
        "elevation": None,
        "country_code": "ID",
        "country": "Indonesia",
        "admin1": "Riau",
        "admin2": "Rokan Hilir Regency",
        "admin3": "",
        "timezone": "Asia/Jakarta",
        "population": None,
        "source": "Manual correction based on validated coordinate",
    },
    {
        "province": "DKI Jakarta",
        "city_regency": "Jakarta Timur",
        "selection_basis": SELECTION_BASIS,
        "selection_method": SELECTION_METHOD,
        "geocoding_query": "Jakarta Timur",
        "matched_name": "Jakarta Timur",
        "latitude": -6.225000,
        "longitude": 106.900444,
        "elevation": None,
        "country_code": "ID",
        "country": "Indonesia",
        "admin1": "Jakarta",
        "admin2": "East Jakarta Administrative City",
        "admin3": "",
        "timezone": "Asia/Jakarta",
        "population": None,
        "source": "Manual correction based on validated coordinate",
    },
    {
        "province": "DKI Jakarta",
        "city_regency": "Jakarta Selatan",
        "selection_basis": SELECTION_BASIS,
        "selection_method": SELECTION_METHOD,
        "geocoding_query": "Jakarta Selatan",
        "matched_name": "Jakarta Selatan",
        "latitude": -6.261490,
        "longitude": 106.810600,
        "elevation": None,
        "country_code": "ID",
        "country": "Indonesia",
        "admin1": "Jakarta",
        "admin2": "South Jakarta Administrative City",
        "admin3": "",
        "timezone": "Asia/Jakarta",
        "population": None,
        "source": "Manual correction based on validated coordinate",
    },
    {
        "province": "DKI Jakarta",
        "city_regency": "Jakarta Barat",
        "selection_basis": SELECTION_BASIS,
        "selection_method": SELECTION_METHOD,
        "geocoding_query": "Jakarta Barat",
        "matched_name": "Jakarta Barat",
        "latitude": -6.168329,
        "longitude": 106.758850,
        "elevation": None,
        "country_code": "ID",
        "country": "Indonesia",
        "admin1": "Jakarta",
        "admin2": "West Jakarta Administrative City",
        "admin3": "",
        "timezone": "Asia/Jakarta",
        "population": None,
        "source": "Manual correction based on validated coordinate",
    },
    {
        "province": "DKI Jakarta",
        "city_regency": "Jakarta Utara",
        "selection_basis": SELECTION_BASIS,
        "selection_method": SELECTION_METHOD,
        "geocoding_query": "Jakarta Utara",
        "matched_name": "Jakarta Utara",
        "latitude": -6.145138,
        "longitude": 106.899452,
        "elevation": None,
        "country_code": "ID",
        "country": "Indonesia",
        "admin1": "Jakarta",
        "admin2": "North Jakarta Administrative City",
        "admin3": "",
        "timezone": "Asia/Jakarta",
        "population": None,
        "source": "Manual correction based on validated coordinate",
    },
    {
        "province": "Kalimantan Tengah",
        "city_regency": "Kapuas",
        "selection_basis": SELECTION_BASIS,
        "selection_method": SELECTION_METHOD,
        "geocoding_query": "Kuala Kapuas",
        "matched_name": "Kuala Kapuas",
        "latitude": -3.001300,
        "longitude": 114.391600,
        "elevation": None,
        "country_code": "ID",
        "country": "Indonesia",
        "admin1": "Central Kalimantan",
        "admin2": "Kapuas Regency",
        "admin3": "",
        "timezone": "Asia/Jakarta",
        "population": None,
        "source": "Manual correction based on validated coordinate",
    },
    {
        "province": "Sulawesi Utara",
        "city_regency": "Minahasa Selatan",
        "selection_basis": SELECTION_BASIS,
        "selection_method": SELECTION_METHOD,
        "geocoding_query": "Amurang",
        "matched_name": "Amurang",
        "latitude": -1.182500,
        "longitude": 124.573000,
        "elevation": None,
        "country_code": "ID",
        "country": "Indonesia",
        "admin1": "North Sulawesi",
        "admin2": "South Minahasa Regency",
        "admin3": "",
        "timezone": "Asia/Makassar",
        "population": None,
        "source": "Manual correction based on validated coordinate",
    },
    {
        "province": "Sulawesi Selatan",
        "city_regency": "Sidenreng Rappang",
        "selection_basis": SELECTION_BASIS,
        "selection_method": SELECTION_METHOD,
        "geocoding_query": "Pangkajene Sidenreng",
        "matched_name": "Pangkajene Sidenreng",
        "latitude": -3.9258194,
        "longitude": 119.7953000,
        "elevation": None,
        "country_code": "ID",
        "country": "Indonesia",
        "admin1": "South Sulawesi",
        "admin2": "Sidenreng Rappang Regency",
        "admin3": "Maritengngae",
        "timezone": "Asia/Makassar",
        "population": None,
        "source": "Manual correction based on validated coordinate",
    },
]

df = pd.DataFrame(rows)

OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
df.to_csv(OUTPUT_PATH, index=False, encoding="utf-8-sig")

print("Manual correction berhasil dibuat:")
print(OUTPUT_PATH)
print("Rows:", len(df))